/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.aginskiy.api;

import com.aginskiy.core.Utils;

public class App {

    public static void main(String[] args) {
        System.out.println(Utils.isAllPositiveNumbers());
    }
}
